### ISSUE TITLE
Duplicate child method parameter error message

### ISSUE THREAD

**Issue by Leland-Takamine** [uber/motif#138]
This message appears to be confusing to folks. Update to a more intuitive error message.

**Comment by mcassiano** [comment]
Is that the message added in #126? Could it possibly use more motif language, like dynamic dependency? Something like:

"[Child ]Scope method has duplicated dynamic dependency types"

**Comment by Leland-Takamine** [comment]
Actually the report I received wanted something specifying that it was multiple params of the same type, but that is already mentioned in the error message. I'll close this out.
