### ISSUE TITLE
Could not find com.uber.motif:motif-ast:0.3.0.

### ISSUE THREAD

**Issue by AllanHasegawa** [uber/motif#157]
**Library version**: 0.3.0

**Repro steps or stacktrace**:

Update motif version from 0.2.1 to 0.3.0, you get this error message:

```
Could not find com.uber.motif:motif-ast:0.3.0.
Required by:
    project :app > com.uber.motif:motif-compiler:0.3.0 > com.uber.motif:motif-ast-compiler:0.3.0
    project :app > com.uber.motif:motif-compiler:0.3.0 > com.uber.motif:motif-core:0.3.0 > com.uber.motif:motif-models:0.3.0
```

The module `motif-ast` is not available for the 0.3.0 version:
https://search.maven.org/search?q=com.uber.motif

**Comment by Leland-Takamine** [comment]
Deployed a new version to fix the issue. Please try out `0.3.1` and reopen this issue if you run into the same problem.
