### ISSUE TITLE
Motif Intellij Plugin: Search Capability

### ISSUE THREAD

**Issue by kasrauber** [uber/motif#194]
Feature Request:
motif plugin is extremely useful! Thanks for build it. However, it's hard to find a scope that's deep in the hierarchy. I can start typing the Scope name, but if it's off screen, the plugin doesn't auto scroll to the scope. In a project with 100s of scopes it's hard to find the scope.

Maybe there is already a way to do this and I am not aware of it?

**Comment by oliviernotteghem** [comment]
@kasrauber : thanks for your feedback. Search support has been implemented, and is being rolled out in the next version of plugin. It's pending approval, but usually takes less than 48 hours.
