### ISSUE TITLE
@motif.Objects silently accepts presence of static methods. 

### ISSUE THREAD

**Issue by andreasnomikos** [uber/motif#20]
**SNAPSHOT**:

    @motif.Objects
    abstract class Objects {
      abstract Router router();

      abstract Interactor interactor();

      abstract Presenter presenter(); // Presenter(MyView view);

      @UIEffect
      static MyView view(ViewGroup parentViewGroup) {
        return new MyView(parentViewGroup.getContext());
      }
    }

Expected:
compiler throws error saying that static methods are not part of the @motif.Objects api 
OR 
compiler accepts definition and sets ScopeImpl.Dependencies to ViewGroup

Current:
compiler ignores definition and sets ScopeImpl.Dependencies to MyView

**Comment by Leland-Takamine** [comment]
Good catch - I'll update this soon.
