### ISSUE TITLE
To allow consumers to add listeners to listen to events like Scope constructor is called, or a factory method is called etc

### ISSUE THREAD

**Issue by Ericliu001** [uber/motif#208]
**Problem:**
Want to track unused scopes in runtime (code that's being called anymore in runtime).

**Solution**
To allow consumers of Motif to add a listener to listen to events.
```
public void  main() {
    //...
    Motif.addUsageListener(listener)
}
```

And the listener class may contain methods indicating a factory method or a scope's constructor is called.
```
interface Listener {
    // ...
    void onScopeConstructorCalled(String ScopeClassName);
}
```
**Proposal**
To handle an **compilerArgs** `-Amotif.tracking=true`
If the parameter is true. Insert code to `motif.compiler.JavaCodeGenerator#spec(motif.compiler.Constructor)`
The generated ScopeImpl.class' constructur would look like this:
```
class ScopeImpl{
  public ScopeImple(A a, B b, C c, ...) {
     this.a = a;
     this.b = b;
     ...
     Tracker.track(scopeClassName);
  }
}
```

And the Tracker class looks like:
```
class Tracker {
  public void registerListener(Listener listener){
  
  }

  public void track(String className) {
    if (listener != null) {
      listener.onConstructorCalled()
    }
  }
}
```

**Comment by Ericliu001** [comment]
CC @kbabcockuf

**Comment by Ericliu001** [comment]
Hi @Leland-Takamine, I just updated the propose, let me know if this is the way to go.

**Comment by andreasnomikos** [comment]
Why should this be part of the core framework? Shouldn't this be implemented with a separate bytecode tool ?

**Comment by Ericliu001** [comment]
> Why should this be part of the core framework? Shouldn't this be implemented with a separate bytecode tool ?

Since there is an option to turn this on and off, it doesn't have any negative effect for average users. For advanced users, having the ability to add listeners to motif framework would be a common use case similar to adding interceptors to OkHttp.

**Comment by TonyTangAndroid** [comment]
Maybe we could follow the pattern like AutoValue extension and introduce Motif Extension?

**Comment by andreasnomikos** [comment]
I know javac is a bit obtuse with the restrictions on bytecode generation and the missing proper compiler api, However if we targeted kotlin-only we would probably be better served to leave this functionality to a separate compiler plugin especially if the use case is side-effects only like monitoring.
The downside of introducing these kind of optional compilerArg based features is severely increasing the complexity of the api and implementation.

Maybe there is a middle ground like @TonyTangAndroid suggested, by framing it as a fully-fledged extension mechanism, but then we should consider all the potential places we would like to add extension hooks and how those "plugins/extensions" are optimally generated/registered/used.

**Comment by tyvsmith** [comment]
This feels too specific the general API. I'd recommend we either consider an approach like @TonyTangAndroid mentioned and establish an extensions API (maybe templates?), or resolve this via bytecode generation. 

I would be cautious at looking to AutoValue for a model here, as opposed to something like Dagger. A DI graph lends towards being fully statically analyzable, and this runtime component doesn't feel quite right.

**Comment by Ericliu001** [comment]
Opted to use bytecode tools
