### ISSUE TITLE
Build sometimes fail in kotlin code generation mode

### ISSUE THREAD

**Issue by Rajin9601** [uber/motif#209]
**Library version**: 0.3.4

Builds from Android Studio sometimes break because of the motif generated file.
The stacktrace was similar to #188.
While debugging why this happens, I found the repro steps.

## Repro Steps

Execute the following commands in motif repo's current master branch. (f95ecde02e1443a1)
```
./gradlew clean
./gradlew samples:sample-kotlin:assembleDebug
./gradlew samples:sample-kotlin:assembleDebug --rerun-tasks
```

Second assemble command will fail with the following error

```
> Task :samples:sample-kotlin:compileDebugKotlin FAILED
e: ..../motif/samples/sample-kotlin/src/main/java/motif/sample/MainActivity.kt: (24, 40): Unresolved reference: MainScopeImpl

FAILURE: Build failed with an exception.
```

## Reason why build fails

When the first build finishes, MainScopeImpl.kt is generated.
When the second build is triggered, kapt generates stub for kotlin files including the generated kotlin files.
(You can find the stub file after the second build fails)

This makes motif compiler think that MainScopeImpl is already generated and [skip the code generation](https://github.com/uber/motif/blob/f95ecde02e1443a14cf8e5a6811fde1db8708f6a/compiler/src/main/kotlin/motif/compiler/ScopeImplFactory.kt#L42) for MainScopeImpl when there will be no MainScopeImpl since kapt will erase the previous generated files.

This issue doesn't happen when motif.mode is changed to java.

**Comment by idanakav** [comment]
@Rajin9601 thank you for reporting the issue.
kapt was recently updated along with kotlin and the issue is no longer reproducible.
