### ISSUE TITLE
Add KSP support

### ISSUE THREAD

**Issue by idanakav** [uber/motif#211]
For Kotlin Motif currently uses kapt to generate code, writing annotation processors with [KSP](https://github.com/google/ksp) are capable of running 2x faster due to the fact that there is no `javac` involved and there is no need to generate stubs while KSP will use the kotlin compiler directly.

There are some limitations such as it's still in development stage and it is not fully compatible with java annotation processing so opening a discussion here whether we would like to pursue this option.

**Comment by andreasnomikos** [comment]
I would be interested in this.

**Comment by tyvsmith** [comment]
+1, the time is right to investigate what this will look like. Much of KSP being in development stage will relate to the underlying kotlinc apis not being stable, so can't expect to wait for that before moving forward.
