### ISSUE TITLE
Does this work w/ kapt?

### ISSUE THREAD

**Issue by kenyee** [uber/motif#39]
Added this to my build.gradle

```
    kapt "com.uber.motif:motif-compiler:${motifVersion}"
    api "com.uber.motif:motif:${motifVersion}"
```

and tried to follow the sample, but RootFactoryImpl doesn't get generated.

**Comment by Leland-Takamine** [comment]
Thanks for raising this - I'll put an example of Kotlin usage. Tracking here #40.

**Comment by Leland-Takamine** [comment]
Added an example of how to use with kapt here: #41.

Perhaps you forgot to add this line in your build.gradle?

```gradle
apply plugin: 'kotlin-kapt'
```

**Comment by kenyee** [comment]
we added Kotlin into the project last year, so definitely not missing that apply plugin.  We actually have all three in all modules:

```
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
```

Back to trying to figure out how to debug this.  Tried doing:

```
gradle assembleKayakFreeDebug --debug | grep -i motif
```
but didn't see any helpful debug logging.  Took out the RootFactory and even the RootScopeImpl doesn't seem to be generated.  Will post back if I figure out why...going to try getting Dagger2 working in the same branch since Motif should interop and maybe that will give me a clue...

**Comment by Leland-Takamine** [comment]
If you're able to send over a stripped down repo case I can try to debug on my end too.

**Comment by Leland-Takamine** [comment]
@kenyee Were you able to figure this out?

**Comment by kenyee** [comment]
Sorry, haven't circled back yet...been trying to get Koin integrated better into our app and remove the old home grown service locator which is everywhere including unit tests :-(
I'll close this for now and re-open if I set up a good small repro sample.

**Comment by Ericliu001** [comment]
Hi @kenyee, have you ran into problem using `ScopeFactory` when using `kapt`? 
#220
