### ISSUE TITLE
Better error messaging for InvalidScopeMethods

### ISSUE THREAD

**Issue by andreasnomikos** [uber/motif#75]
**Library version**: 0.0.13

**Repro steps or stacktrace**:

Forgetting the @motif.Scope annotation on a child module throws a non-descriptive error

@motif.Scope
interface ParentScope {
  ChildScope childScope();
}

interface ChildScope {

}

```
Command failed with exit code 1.
stderr: : error: 

  Invalid Scope method.
Errors: 1. Warnings: 0.

    When running <javac_jar>.
    When building rule //libraries/feature/emobility/search:src_release.
```

**Comment by Leland-Takamine** [comment]
#137
