### ISSUE TITLE
@Named dependency is used implicitly

### ISSUE THREAD

**Issue by dmitry-zaitsev** [uber/motif#87]
**Library version**: 0.0.18-SNAPSHOT (commit hash: cfbcea30b540057bf4f4a8a33f2415e9906b6ec8)

**Repro steps or stacktrace**:

Use the following setup:

```
@motif.Scope
public interface Scope {

    Child child();

    @motif.Objects
    abstract class Objects {

        @Named("a")
        String value() {
            return "value";
        }

    }

}

public class Child {

    public Child(String value) {}

}
```

**Expected behaviour**:

`Child` dependencies are not satisfied because unnamed `String` is not in a DI graph.

**Actual behaviour**:

Compilation passes and `@Named("a")` is used in place of unnamed `String`.

**Comment by Leland-Takamine** [comment]
I'd expect this to compile because we are not enforcing which dependencies `Scope` should expect from its parent. Can you try adding a `@Dependencies` interface to `Scope`?

```
@motif.Dependencies
interface Dependencies {}
```

**Comment by dmitry-zaitsev** [comment]
Adding `@Dependencies` causes compilation to fail, which means that this issue is not really valid.

The reason why I brought this up is because while doing migration from Dagger to Motif I encountered a class like that:

```
class MyInteractor {

    @Named("a")
    Child child;

    MyInteractor(Child child) {
        this.child = child;
    }

}
```

My first (incorrect) assumption was that named `Child` is being used instead of an unqualified version. But it turned out that unqualified `Child` was provided by some of the parent scopes. 

I did not double check that, but I believe that `@Named` annotation on a field is ignored in that case. Is that correct?

**Comment by Leland-Takamine** [comment]
That's correct - if you're using a constructor factory method, then Motif looks at the constructor, which means you'll need to annotate the parameters instead of the field.

**Comment by dmitry-zaitsev** [comment]
In that case, having a `@Named` annotation on the field might mislead developer into thinking that a different dependency is being used. I think it would make sense to fail compilation in that case.

**Comment by Leland-Takamine** [comment]
Agree, but this is something that should be implemented as an error prone check. We wouldn't want to build it into the Motif compiler since the the field may be annotated for other reasons.

**Comment by Leland-Takamine** [comment]
Closing this out. @dmitry-zaitsev feel free to re-open if needed.
