### ISSUE TITLE
[Proposal] Explicit Scope Input

### ISSUE THREAD

**Issue by dmitry-zaitsev** [uber/motif#88]
## Abstract
Quite often scopes have a set of dependencies which is expected to be provided by a direct parent of that Scope. For example, that includes:

- Listeners
- Input data (i.e. collection of POJOs)

Currently, Motif has few problems when working with such cases.

### Implicity

It is not possible to tell which dependencies are expected to be provided by the immediate parent and which are expected to come from a general DI graph. Take this example:

```
@Scope
public interface BookStoreScope {

 BookStoreInteractor bookStoreInteractor();

 @motif.Objects
 abstract class Objects {

   abstract BookStoreInteractor interactor();

 }
}
```

This Scope, in fact, expects a `Listener` and `List<Book>` as its input, but it is nowhere to be seen as the Scope definition does not list those explicitly.

### Unintentional Reuse

Going back to BookStoreScope example, it is possible that one of the parent scopes is already exposing some of the required dependencies. Integrating BookStoreScope in a new parent scope could result in unintentional reuse of the dependency from a DI graph instead of the one provided by a direct parent. In turn, that will cause problems if, for example, the expected dependency is a `Listener`.

## Proposed Solution

Declare direct inputs explicitly by using an `@Inputs` section.

In addition to that, `BookStoreScopeInputs` POJO will be auto-generated which will need to be passed to parent’s scope builder method as an input argument. 

This would prevent developers from accidentally reusing dependencies as now they would need to explicitly pass it as an argument to a scope builder.

```
@Scope
public interface BookStoreScope {

 BookStoreInteractor bookStoreInteractor();

 @motif.Inputs
 interface Inputs {

   Listener listener();

   List<Book> books();

 }


 @motif.Objects
 abstract class Objects {

   abstract BookStoreInteractor interactor();

 }
}
```

**Comment by andreasnomikos** [comment]
This seems like a specific architecture concern. In practice I can have listeners that come from 2 levels up depending on how I decompose the Scope graph. As far as motif is concerned the scope doesn't specify if it wants the dependencies to be provided dynamically or statically and delegates that responsibility to the parent. 

This functionality can be implemented as an additional erroprone checker if we consider modularizing/exposing the motif IR and parser, but I would not roll it into the main framework.

**Comment by Ericliu001** [comment]
I agree with @andreasnomikos, and I actually like the fact that in motif, the child scope doesn't have the notion of whether a dependency is passed down dynamically or statically or from 2 levels up or the from the immediate parent. 
As a result, the child scope is completely decoupled from the parent. 

In practice, the problem presented here could be solved once the IntelliJ plugin is completed and programmers can see where the dependency is from by looking at a visual diagram.

**Comment by dmitry-zaitsev** [comment]
Alright, I think those are fair points. I will look at other ways to solve those problems.

**Comment by Leland-Takamine** [comment]
Good discussion - I understand the use case, but agree with the conclusion here and still advocate for the original design decision to keep the child completely decoupled from the parent.
